### ISSUE TITLE
Using Scala 3 seriously breaks default value handing

### ISSUE THREAD

**Issue by strelec** [com-lihaoyi/upickle#362]
Minimal example:

```scala
case class A(a: Int = 1)

import upickle.default._
implicit val rw: ReadWriter[A] = macroRW[A]

println(read[A]("{\"a\":2}"))
println(read[A]("{}"))
```

Expected (upickle 1.4.0, Scala 2.13.6):
```
A(2)
A(1)
```

Got (upickle 1.4.0, Scala 3.0.1):
```
A(2)
A(2)
```

God knows how many projects are silently corrupting their databases. Or leaking data from another user in their API calls. Since the parser is keeping and leaking state, everything is possible.

**Comment by jodersky** [comment]
There is a known issue indeed, but please keep in mind that we're all volunteers here and have other activities in our lives. Sometimes we can't immediately fix a bug when one is reported. Pull requests with fixes are welcome any time however.

As for this issue in particular, note that upickle was one of the first macro-heavy libraries ported to Scala 3 while it was still called Dotty. We uncovered some bugs in the Dotty compiler itself during the effort, and sometimes had to adapt test suites in order to move forward. The goal of course is always to write correct code, but sometimes things slip through.

As for the release, it is managed by an automatic process. Furthermore, I don't think anyone is served by stopping to provide a library which has already been published and is functional in almost all regards except for a few issues, regardless of their severity.

**Comment by strelec** [comment]
I know you are volunteers. I also think mr. Li took too much burden to carry. The result is a lot of sporadically supported libraries, which is unfortunate. :(

The only thing I was suggesting is to omit Scala 3 support from the future releases, until the issues are fixed. Above we talked about unpublishing, which is not possible. But not publishing more broken versions is reasonable.

I have already written my own Scala 3 macros for JSON pickling, so no support needed for me. I am merely on this thread for other peoiple, as this bug could have disastrous consequences (privacy leaks and database corruption) and I have discovered it.

**Comment by lihaoyi** [comment]
@jodersky if I'm not mistaken I think this is the fix

```diff
lihaoyi upickle$ git diff
diff --git a/build.sc b/build.sc
index 133b30f..8664795 100644
--- a/build.sc
+++ b/build.sc
@@ -14,7 +14,7 @@ import com.github.lolgab.mill.mima._
 val scala211  = "2.11.12"
 val scala212  = "2.12.13"
 val scala213  = "2.13.4"
-val scala3    = "3.0.0"
+val scala3    = "3.0.2"
 val scalaJS06 = "0.6.33"
 val scalaJS1  = "1.5.1"
 val scalaNative = "0.4.0"
diff --git a/implicits/src-3/upickle/implicits/CaseClassReader.scala b/implicits/src-3/upickle/implicits/CaseClassReader.scala
index de66b16..e21a6b1 100644
--- a/implicits/src-3/upickle/implicits/CaseClassReader.scala
+++ b/implicits/src-3/upickle/implicits/CaseClassReader.scala
@@ -11,9 +11,8 @@ trait CaseClassReaderPiece extends MacrosCommon:

     def visitorForKey(currentKey: String): Visitor[_, _]

-    private val builder = collection.mutable.Map.empty[String, Any]
-
     override def visitObject(length: Int, index: Int) = new ObjVisitor[Any, T] {
+      private val builder = collection.mutable.Map.empty[String, Any]
       var currentKey: String = null

       def subVisitor: Visitor[_, _] = visitorForKey(currentKey)
diff --git a/implicits/src-3/upickle/implicits/CaseClassWriter.scala b/implicits/src-3/upickle/implicits/CaseClassWriter.scala
index f2802c0..f49368c 100644
--- a/implicits/src-3/upickle/implicits/CaseClassWriter.scala
+++ b/implicits/src-3/upickle/implicits/CaseClassWriter.scala
@@ -14,8 +14,8 @@ trait CaseClassWriterPiece extends MacrosCommon:
       var n = 0
       for
         (name, _, value) <- elemsInfo(v)
-        defaultValue <- defaultParams.get(name)
-        if defaultValue != value || serializeDefaults
+        defaultValue = defaultParams.get(name)
+        if serializeDefaults || defaultValue.isEmpty || defaultValue.get != value
       do n += 1
       n
     end length
```
